# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"
env:
- TOXENV=py27
install:
- pip install -U wheel
- pip install -U tox
# command to run tests, e.g. python setup.py test
script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: "EviWl7/ssRUYyfcQ2G1o+8lc8kLmy0dpLxSDgVerwEmhFWMem+dyfvfGQk7C8C3yDO3J0BrvgbZLj5/UgZRp3lz3imV7b+iQ8ITLYWAU6X8/+XbQ+xcwNfnzxg9Pj1CLXu4CBvT5biSTJ969K2w5lm5l9J/TIqTp9VfypikOgf0="
  on:
    tags: true
    repo: scrapinghub/dateparser
    condition: "$TOXENV == py27"
